version: '3'

services:
  ### MySQL
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./volumes/data/mysql:/var/lib/mysql
    networks:
      - my_network


networks:
  my_network:
    driver: bridge
