version: '3'

services:
  ### MySQL
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./volumes/data/mysql:/var/lib/mysql
    networks:
      - my_network

  # Zookeeper 서비스
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - my_network

  # Kafka 서비스
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME_INSIDE: INSIDE
      KAFKA_LISTENER_PORT: 9093
      KAFKA_LISTENER_INTERFACE: eth0
      KAFKA_LISTENERS: INSIDE://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
