server:
  port: 8000

spring:
  application:
    name: store-service

  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: testuser  #root
    password: testpass  #1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092  # Kafka 서버 주소
    consumer:
      group-id: test-group             # Kafka Consumer의 그룹 ID
      auto-offset-reset: earliest      # 오프셋이 없을 때 처리 방식 (earliest: 처음부터)
      enable-auto-commit: false        # 자동 커밋 비활성화 (수동 커밋으로 처리)
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer  # Key Serializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer  # Value Serializer

setting:
  topics: my-topic                    # 소비할 Kafka 토픽 설정
  autocommit: false                   # 오토 커밋 여부 설정
  earliest: earliest                  # Kafka의 오프셋 초기 설정 (earliest 또는 latest)